### ISSUE TITLE
Test on Windows

### ISSUE THREAD

**Issue by kschuler** [kschuler/words-in-noise-EEG#14]
- fix OS call

**Comment by kschuler** [comment]
Added to the param file:

```yaml
devices:
    eeg:
        computer_os: 'OSX'                  # OSX or XP
        ip: 0.0.0.0                         # ip address of netstation
```
